version: '3.3'
services:
    stash1:
        image: stashapp/stash:latest
        container_name: stash1
        restart: unless-stopped
        ports:
            - 9999:9999
        volumes:
            - ./media:/media
            - ./config/stash1:/root/.stash
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
    api:
        ports:
            - '5000:5000'
        build: .