FROM python:alpine

RUN mkdir -p /app
WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY ./main.py /app/main.py
COPY ./test.py /app/test.py


EXPOSE 5000


CMD ["python3", "main.py"]